USE [master]
GO

/****** Object:  Database [clientes_db]    Script Date: 27/03/2021 20:48:54 ******/
CREATE DATABASE [clientes_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'clientes_db', FILENAME = N'C:\MSSQL\DATA\clientes_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'clientes_db_log', FILENAME = N'C:\MSSQL\DATA\clientes_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [clientes_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [clientes_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [clientes_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [clientes_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [clientes_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [clientes_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [clientes_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [clientes_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [clientes_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [clientes_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [clientes_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [clientes_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [clientes_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [clientes_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [clientes_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [clientes_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [clientes_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [clientes_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [clientes_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [clientes_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [clientes_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [clientes_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [clientes_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [clientes_db] SET RECOVERY FULL 
GO

ALTER DATABASE [clientes_db] SET  MULTI_USER 
GO

ALTER DATABASE [clientes_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [clientes_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [clientes_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [clientes_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [clientes_db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [clientes_db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [clientes_db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [clientes_db] SET  READ_WRITE 
GO


USE [clientes_db]
GO

/****** Object:  Table [dbo].[Cliente]    Script Date: 27/03/2021 21:29:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cliente](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NOT NULL,
	[CPF] [varchar](15) NOT NULL,
	[telefone] [varchar](15) NULL
) ON [PRIMARY]
GO

